##
##  Makefile -- Build procedure for sample mod_wurfl Apache module
##  Autogenerated via ``apxs -n mod_wurfl -g''.
##

builddir=.
top_srcdir=/home/cmaser/apachedev
top_builddir=/home/cmaser/apachedev
include /home/cmaser/apachedev/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_wurfl.o mod_wurfl.lo mod_wurfl.slo mod_wurfl.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/mod_wurfl

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

